#!/usr/bin/env expect

set project piperider-getting-started
set project_url https://github.com/InfuseAI/piperider-getting-started.git
set timeout 60

# start from getting the project
exec -ignorestderr -- git clone $project_url
cd $project

# download the first dataset
exec -ignorestderr -- curl -o data/sp500.db https://piperider-data.s3.ap-northeast-1.amazonaws.com/getting-started/sp500_20220401.db

# check the diagnose
set title "check out with the first dataset"
spawn piperider diagnose --debug
expect {
    "You are all set" {
        pass $title
    }
    eof {
        fail $title
    }
}

set title "run with the first dataset"
spawn piperider run --no-interaction --debug

expect {
    "Report generated in" {
        # TODO check the single report
        pass $title
    }
    eof {
        fail $title
    }
}

# download the second dataset
exec -ignorestderr -- curl -o data/sp500.db https://piperider-data.s3.ap-northeast-1.amazonaws.com/getting-started/sp500_20220527.db

set title "run with the second dataset"
spawn piperider run --no-interaction --debug

expect {
    "Report generated in" {
        # TODO check the single report
        pass $title
    }
    eof {
        fail $title
    }
}
