#!/usr/bin/env expect

set project piperider-getting-started
set timeout 60
cd $project

set title "compare-reports step started"
spawn piperider compare-reports
expect {
    "Please select the 2 reports to compare" {
        # wait for list
        after 3000
        pass $title
    }
    eof {
        fail $title
    }
}


set title "compare-reports step ended"

expect {
    "> o" {
        send " "
        after 500
        send "\[B"
        after 500
        exp_continue
    }
    "> X" {
        after 1000
        send "\r"
        exp_continue
    }
    "not a valid profiler_outputs" {
        send "a"
        exp_continue
    }
    "Comparison report" {
        pass $title
    }
    eof {
        fail $title
    }
}

puts "Finished."
