export const schemaMetaDescriptions = {
  total: 'the total count of values, regardless validity',
  nulls: 'the count of values that are null type',
  non_nulls: 'The count of non null values',
  distinct: 'The count of distinct kinds of values (e.g. [a,b,c,c] => [a,b,c])',
  topk: 'The statistical mode value of the most common or frequent value',
  name: 'name of this column',
  description: 'descriptor of this column',
  type: 'Generic types of schema, python-based',
  schema_type: 'The column type definition in SQL database',
  valids: 'the count of values that are non-null and not invalid',
  invalids: 'the count of values that are non-null and invalid',
  zeros: 'count of numerical values that equal zero exactly',
  negatives: 'count of numerical values that are less than zero',
  positives: 'count of numerical values that are more than zero',
  zero_length: 'count of string values with zero lengths exactly',
  non_zero_length: 'count of string values with non-zero lengths',
  trues: 'count of boolean true values',
  falses: 'count of boolean false values',
  duplicates:
    'The count of values that are recurring (e.g. [a,b,c,c] => [c,c])',
  non_duplicates:
    'The count of values that are non-recurring (e.g. [a,b,c,c] => [a,b])',
  sum: 'The sum of all dataset values',
  avg: 'the mean average statistic of dataset',
  stddev: 'the standard deviation statistic of dataset',
  min: "The minimum value of the dataset's quantiles; can be numerical or datetime string",
  max: "The maximum value of the dataset's quantiles; can be numerical or datetime string",
  p5: 'The quantile value of the dataset (5th percentile)',
  p25: 'The quantile value of the dataset (25th percentile)',
  p50: 'The quantile value of the dataset (50th percentile)',
  p75: 'The quantile value of the dataset (75th percentile)',
  p95: 'The quantile value of the dataset (95th percentile)',
};
