export const schemaMetaDescriptions = {
  total: 'The total count of values, regardless validity',
  nulls: 'The count of values that are null type',
  non_nulls: 'The count of non null values',
  distinct: 'The count of distinct kinds of values (e.g. [a,b,c,c] => [a,b,c])',
  duplicates:
    'The count of values that are recurring (e.g. [a,b,c,c] => [c,c])',
  non_duplicates:
    'The count of values that are non-recurring (e.g. [a,b,c,c] => [a,b])',
  topk: 'The most common or frequent value',
  name: 'Name of this column',
  description: 'Descriptor of this column',
  type: 'Generic types of schema, python-based',
  schema_type: 'The column type definition in SQL database',
  valids: 'The count of values that are non-null and not invalid',
  invalids:
    "The count of values that don't match the schema type. For example, a string in a numeric column.",
  zeros: 'The count of numerical values that equal zero exactly',
  negatives: 'The count of numerical values that are less than zero',
  positives: 'The count of numerical values that are more than zero',
  zero_length: 'The count of string values with zero lengths exactly',
  non_zero_length: 'The count of string values with non-zero lengths',
  trues: 'The count of boolean true values',
  falses: 'The count of boolean false values',
  sum: "The sum of a column's values",
  avg: "The average of a column's values",
  stddev: "The standard deviation of a column's values",
  min: "The minimum value of a column's range",
  max: "The maximum value of a columns's range",
  p5: 'The quantile value of the dataset (5th percentile)',
  p25: 'The quantile value of the dataset (25th percentile)',
  p50: 'The quantile value of the dataset (50th percentile)',
  p75: 'The quantile value of the dataset (75th percentile)',
  p95: 'The quantile value of the dataset (95th percentile)',
};
