/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface SingleReportSchema {
  tables?: {
    ACTION?: {
      name?: string;
      row_count?: number;
      col_count?: number;
      columns?: {
        SYMBOL?: {
          total?: number;
          non_nulls?: number;
          distinct?: number;
          distribution?: {
            type?: string;
            labels?: string[];
            counts?: number[];
            [k: string]: unknown;
          };
          name?: string;
          profile_duration?: string;
          type?: string;
          schema_type?: string;
          [k: string]: unknown;
        };
        DATE?: {
          total?: number;
          non_nulls?: number;
          mismatched?: number;
          distinct?: number;
          min?: string;
          max?: string;
          distribution?: {
            type?: string;
            labels?: string[];
            counts?: number[];
            [k: string]: unknown;
          };
          name?: string;
          profile_duration?: string;
          type?: string;
          schema_type?: string;
          [k: string]: unknown;
        };
        DIVIDENDS?: {
          total?: number;
          non_nulls?: number;
          mismatched?: number;
          distinct?: number;
          min?: number;
          max?: number;
          sum?: number;
          avg?: number;
          p5?: number;
          p25?: number;
          stddev?: number;
          p50?: number;
          p75?: number;
          p95?: number;
          distribution?: {
            type?: string;
            labels?: string[];
            counts?: number[];
            bin_edges?: number[];
            [k: string]: unknown;
          };
          name?: string;
          profile_duration?: string;
          type?: string;
          schema_type?: string;
          [k: string]: unknown;
        };
        SPLITS?: {
          total?: number;
          non_nulls?: number;
          mismatched?: number;
          distinct?: number;
          min?: number;
          max?: number;
          sum?: number;
          avg?: number;
          p5?: number;
          p25?: number;
          stddev?: number;
          p50?: number;
          p75?: number;
          p95?: number;
          distribution?: {
            type?: string;
            labels?: string[];
            counts?: number[];
            bin_edges?: number[];
            [k: string]: unknown;
          };
          name?: string;
          profile_duration?: string;
          type?: string;
          schema_type?: string;
          [k: string]: unknown;
        };
        [k: string]: unknown;
      };
      assertion_results?: {
        tests?: {
          name?: string;
          status?: string;
          parameters?: {
            [k: string]: unknown;
          };
          expected?: {
            min?: number;
            [k: string]: unknown;
          };
          actual?: number;
          tags?: string[];
          [k: string]: unknown;
        }[];
        columns?: {
          SYMBOL?: {
            name: string;
            status: string;
            parameters: {
              [k: string]: unknown;
            };
            expected: {
              schema_type?: string;
              success?: boolean;
              [k: string]: unknown;
            };
            actual: {
              success?: boolean;
              [k: string]: unknown;
            };
            tags: string[];
            [k: string]: unknown;
          }[];
          DATE?: {
            name: string;
            status: string;
            parameters: {
              [k: string]: unknown;
            };
            expected: {
              schema_type?: string;
              success?: boolean;
              [k: string]: unknown;
            };
            actual: {
              success?: boolean;
              [k: string]: unknown;
            };
            tags: string[];
            [k: string]: unknown;
          }[];
          DIVIDENDS?: {
            name: string;
            status: string;
            parameters: {
              [k: string]: unknown;
            };
            expected: {
              schema_type?: string;
              max?: number[];
              success?: boolean;
              [k: string]: unknown;
            };
            actual: {
              max?: number;
              success?: boolean;
              [k: string]: unknown;
            };
            tags: string[];
            [k: string]: unknown;
          }[];
          SPLITS?: {
            name: string;
            status: string;
            parameters: {
              [k: string]: unknown;
            };
            expected: {
              schema_type?: string;
              max?: number[];
              success?: boolean;
              [k: string]: unknown;
            };
            actual: {
              max?: number;
              success?: boolean;
              [k: string]: unknown;
            };
            tags: string[];
            [k: string]: unknown;
          }[];
          [k: string]: unknown;
        };
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
    "PRICE OF SUPER"?: {
      name?: string;
      row_count?: number;
      col_count?: number;
      columns?: {
        SYMBOL?: {
          total?: number;
          non_nulls?: number;
          distinct?: number;
          distribution?: {
            type?: string;
            labels?: string[];
            counts?: number[];
            [k: string]: unknown;
          };
          name?: string;
          profile_duration?: string;
          type?: string;
          schema_type?: string;
          [k: string]: unknown;
        };
        DATE?: {
          total?: number;
          non_nulls?: number;
          mismatched?: number;
          distinct?: number;
          min?: string;
          max?: string;
          distribution?: {
            type?: string;
            labels?: string[];
            counts?: number[];
            [k: string]: unknown;
          };
          name?: string;
          profile_duration?: string;
          type?: string;
          schema_type?: string;
          [k: string]: unknown;
        };
        OPEN?: {
          total?: number;
          non_nulls?: number;
          mismatched?: number;
          distinct?: number;
          min?: number;
          max?: number;
          sum?: number;
          avg?: number;
          p5?: number;
          p25?: number;
          stddev?: number;
          p50?: number;
          p75?: number;
          p95?: number;
          distribution?: {
            type?: string;
            labels?: string[];
            counts?: number[];
            bin_edges?: number[];
            [k: string]: unknown;
          };
          name?: string;
          profile_duration?: string;
          type?: string;
          schema_type?: string;
          [k: string]: unknown;
        };
        HIGH?: {
          total?: number;
          non_nulls?: number;
          mismatched?: number;
          distinct?: number;
          min?: number;
          max?: number;
          sum?: number;
          avg?: number;
          p5?: number;
          p25?: number;
          stddev?: number;
          p50?: number;
          p75?: number;
          p95?: number;
          distribution?: {
            type?: string;
            labels?: string[];
            counts?: number[];
            bin_edges?: number[];
            [k: string]: unknown;
          };
          name?: string;
          profile_duration?: string;
          type?: string;
          schema_type?: string;
          [k: string]: unknown;
        };
        LOW?: {
          total?: number;
          non_nulls?: number;
          mismatched?: number;
          distinct?: number;
          min?: number;
          max?: number;
          sum?: number;
          avg?: number;
          p5?: number;
          p25?: number;
          stddev?: number;
          p50?: number;
          p75?: number;
          p95?: number;
          distribution?: {
            type?: string;
            labels?: string[];
            counts?: number[];
            bin_edges?: number[];
            [k: string]: unknown;
          };
          name?: string;
          profile_duration?: string;
          type?: string;
          schema_type?: string;
          [k: string]: unknown;
        };
        CLOSE?: {
          total?: number;
          non_nulls?: number;
          mismatched?: number;
          distinct?: number;
          min?: number;
          max?: number;
          sum?: number;
          avg?: number;
          p5?: number;
          p25?: number;
          stddev?: number;
          p50?: number;
          p75?: number;
          p95?: number;
          distribution?: {
            type?: string;
            labels?: string[];
            counts?: number[];
            bin_edges?: number[];
            [k: string]: unknown;
          };
          name?: string;
          profile_duration?: string;
          type?: string;
          schema_type?: string;
          [k: string]: unknown;
        };
        VOLUME?: {
          total?: number;
          non_nulls?: number;
          mismatched?: number;
          distinct?: number;
          min?: number;
          max?: number;
          sum?: number;
          avg?: number;
          p5?: number;
          p25?: number;
          stddev?: number;
          p50?: number;
          p75?: number;
          p95?: number;
          distribution?: {
            type?: string;
            labels?: string[];
            counts?: number[];
            bin_edges?: number[];
            [k: string]: unknown;
          };
          name?: string;
          profile_duration?: string;
          type?: string;
          schema_type?: string;
          [k: string]: unknown;
        };
        ADJCLOSE?: {
          total?: number;
          non_nulls?: number;
          mismatched?: number;
          distinct?: number;
          min?: number;
          max?: number;
          sum?: number;
          avg?: number;
          p5?: number;
          p25?: number;
          stddev?: number;
          p50?: number;
          p75?: number;
          p95?: number;
          distribution?: {
            type?: string;
            labels?: string[];
            counts?: number[];
            bin_edges?: number[];
            [k: string]: unknown;
          };
          name?: string;
          profile_duration?: string;
          type?: string;
          schema_type?: string;
          [k: string]: unknown;
        };
        MA5?: {
          total?: number;
          non_nulls?: number;
          mismatched?: number;
          distinct?: number;
          min?: number;
          max?: number;
          sum?: number;
          avg?: number;
          p5?: number;
          p25?: number;
          stddev?: number;
          p50?: number;
          p75?: number;
          p95?: number;
          distribution?: {
            type?: string;
            labels?: string[];
            counts?: number[];
            bin_edges?: number[];
            [k: string]: unknown;
          };
          name?: string;
          profile_duration?: string;
          type?: string;
          schema_type?: string;
          [k: string]: unknown;
        };
        MA20?: {
          total?: number;
          non_nulls?: number;
          mismatched?: number;
          distinct?: number;
          min?: number;
          max?: number;
          sum?: number;
          avg?: number;
          p5?: number;
          p25?: number;
          stddev?: number;
          p50?: number;
          p75?: number;
          p95?: number;
          distribution?: {
            type?: string;
            labels?: string[];
            counts?: number[];
            bin_edges?: number[];
            [k: string]: unknown;
          };
          name?: string;
          profile_duration?: string;
          type?: string;
          schema_type?: string;
          [k: string]: unknown;
        };
        MA60?: {
          total?: number;
          non_nulls?: number;
          mismatched?: number;
          distinct?: number;
          min?: number;
          max?: number;
          sum?: number;
          avg?: number;
          p5?: number;
          p25?: number;
          stddev?: number;
          p50?: number;
          p75?: number;
          p95?: number;
          distribution?: {
            type?: string;
            labels?: string[];
            counts?: number[];
            bin_edges?: number[];
            [k: string]: unknown;
          };
          name?: string;
          profile_duration?: string;
          type?: string;
          schema_type?: string;
          [k: string]: unknown;
        };
        [k: string]: unknown;
      };
      assertion_results?: {
        tests?: {
          name?: string;
          status?: string;
          parameters?: {
            [k: string]: unknown;
          };
          expected?: {
            min?: number;
            [k: string]: unknown;
          };
          actual?: number;
          tags?: string[];
          [k: string]: unknown;
        }[];
        columns?: {
          SYMBOL?: {
            name: string;
            status: string;
            parameters: {
              [k: string]: unknown;
            };
            expected: {
              schema_type?: string;
              success?: boolean;
              [k: string]: unknown;
            };
            actual: {
              success?: boolean;
              [k: string]: unknown;
            };
            tags: string[];
            [k: string]: unknown;
          }[];
          DATE?: {
            name: string;
            status: string;
            parameters: {
              [k: string]: unknown;
            };
            expected: {
              schema_type?: string;
              success?: boolean;
              [k: string]: unknown;
            };
            actual: {
              success?: boolean;
              [k: string]: unknown;
            };
            tags: string[];
            [k: string]: unknown;
          }[];
          OPEN?: {
            name: string;
            status: string;
            parameters: {
              [k: string]: unknown;
            };
            expected: {
              schema_type?: string;
              max?: number[];
              success?: boolean;
              [k: string]: unknown;
            };
            actual: {
              max?: number;
              success?: boolean;
              [k: string]: unknown;
            };
            tags: string[];
            [k: string]: unknown;
          }[];
          HIGH?: {
            name: string;
            status: string;
            parameters: {
              [k: string]: unknown;
            };
            expected: {
              schema_type?: string;
              max?: number[];
              success?: boolean;
              [k: string]: unknown;
            };
            actual: {
              max?: number;
              success?: boolean;
              [k: string]: unknown;
            };
            tags: string[];
            [k: string]: unknown;
          }[];
          LOW?: {
            name: string;
            status: string;
            parameters: {
              [k: string]: unknown;
            };
            expected: {
              schema_type?: string;
              max?: number[];
              success?: boolean;
              [k: string]: unknown;
            };
            actual: {
              max?: number;
              success?: boolean;
              [k: string]: unknown;
            };
            tags: string[];
            [k: string]: unknown;
          }[];
          CLOSE?: {
            name: string;
            status: string;
            parameters: {
              [k: string]: unknown;
            };
            expected: {
              schema_type?: string;
              max?: number[];
              success?: boolean;
              [k: string]: unknown;
            };
            actual: {
              max?: number;
              success?: boolean;
              [k: string]: unknown;
            };
            tags: string[];
            [k: string]: unknown;
          }[];
          VOLUME?: {
            name: string;
            status: string;
            parameters: {
              [k: string]: unknown;
            };
            expected: {
              schema_type?: string;
              max?: number[];
              success?: boolean;
              [k: string]: unknown;
            };
            actual: {
              max?: number;
              success?: boolean;
              [k: string]: unknown;
            };
            tags: string[];
            [k: string]: unknown;
          }[];
          ADJCLOSE?: {
            name: string;
            status: string;
            parameters: {
              [k: string]: unknown;
            };
            expected: {
              schema_type?: string;
              max?: number[];
              success?: boolean;
              [k: string]: unknown;
            };
            actual: {
              max?: number;
              success?: boolean;
              [k: string]: unknown;
            };
            tags: string[];
            [k: string]: unknown;
          }[];
          MA5?: {
            name: string;
            status: string;
            parameters: {
              [k: string]: unknown;
            };
            expected: {
              schema_type?: string;
              max?: number[];
              [k: string]: unknown;
            };
            actual: {
              max?: number;
              [k: string]: unknown;
            };
            tags: string[];
            [k: string]: unknown;
          }[];
          MA20?: {
            name: string;
            status: string;
            parameters: {
              [k: string]: unknown;
            };
            expected: {
              schema_type?: string;
              max?: number[];
              [k: string]: unknown;
            };
            actual: {
              max?: number;
              [k: string]: unknown;
            };
            tags: string[];
            [k: string]: unknown;
          }[];
          MA60?: {
            name: string;
            status: string;
            parameters: {
              [k: string]: unknown;
            };
            expected: {
              schema_type?: string;
              max?: number[];
              [k: string]: unknown;
            };
            actual: {
              max?: number;
              [k: string]: unknown;
            };
            tags: string[];
            [k: string]: unknown;
          }[];
          [k: string]: unknown;
        };
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
    SYMBOL?: {
      name?: string;
      row_count?: number;
      col_count?: number;
      columns?: {
        SYMBOL?: {
          total?: number;
          non_nulls?: number;
          distinct?: number;
          distribution?: {
            type?: string;
            labels?: string[];
            counts?: number[];
            [k: string]: unknown;
          };
          name?: string;
          profile_duration?: string;
          type?: string;
          schema_type?: string;
          [k: string]: unknown;
        };
        NAME?: {
          total?: number;
          non_nulls?: number;
          distinct?: number;
          distribution?: {
            type?: string;
            labels?: string[];
            counts?: number[];
            [k: string]: unknown;
          };
          name?: string;
          profile_duration?: string;
          type?: string;
          schema_type?: string;
          [k: string]: unknown;
        };
        START_DATE?: {
          total?: number;
          non_nulls?: number;
          mismatched?: number;
          distinct?: number;
          min?: string;
          max?: string;
          distribution?: {
            type?: string;
            labels?: string[];
            counts?: number[];
            [k: string]: unknown;
          };
          name?: string;
          profile_duration?: string;
          type?: string;
          schema_type?: string;
          [k: string]: unknown;
        };
        END_DATE?: {
          total?: number;
          non_nulls?: number;
          mismatched?: number;
          distinct?: number;
          min?: string;
          max?: string;
          distribution?: {
            type?: string;
            labels?: string[];
            counts?: number[];
            [k: string]: unknown;
          };
          name?: string;
          profile_duration?: string;
          type?: string;
          schema_type?: string;
          [k: string]: unknown;
        };
        DESCRIPTION?: {
          total?: number;
          non_nulls?: number;
          distinct?: number;
          distribution?: {
            type?: string;
            labels?: string[];
            counts?: number[];
            [k: string]: unknown;
          };
          name?: string;
          profile_duration?: string;
          type?: string;
          schema_type?: string;
          [k: string]: unknown;
        };
        EXCHANGE_CODE?: {
          total?: number;
          non_nulls?: number;
          distinct?: number;
          distribution?: {
            type?: string;
            labels?: string[];
            counts?: number[];
            [k: string]: unknown;
          };
          name?: string;
          profile_duration?: string;
          type?: string;
          schema_type?: string;
          [k: string]: unknown;
        };
        MARKET?: {
          total?: number;
          non_nulls?: number;
          distinct?: number;
          distribution?: {
            type?: string;
            labels?: string[];
            counts?: number[];
            [k: string]: unknown;
          };
          name?: string;
          profile_duration?: string;
          type?: string;
          schema_type?: string;
          [k: string]: unknown;
        };
        COUNTRY?: {
          total?: number;
          non_nulls?: number;
          distinct?: number;
          distribution?: {
            type?: string;
            labels?: string[];
            counts?: number[];
            [k: string]: unknown;
          };
          name?: string;
          profile_duration?: string;
          type?: string;
          schema_type?: string;
          [k: string]: unknown;
        };
        SECTOR?: {
          total?: number;
          non_nulls?: number;
          distinct?: number;
          distribution?: {
            type?: string;
            labels?: string[];
            counts?: number[];
            [k: string]: unknown;
          };
          name?: string;
          profile_duration?: string;
          type?: string;
          schema_type?: string;
          [k: string]: unknown;
        };
        INDUSTRY?: {
          total?: number;
          non_nulls?: number;
          distinct?: number;
          distribution?: {
            type?: string;
            labels?: string[];
            counts?: number[];
            [k: string]: unknown;
          };
          name?: string;
          profile_duration?: string;
          type?: string;
          schema_type?: string;
          [k: string]: unknown;
        };
        RECOMMENDATION_KEY?: {
          total?: number;
          non_nulls?: number;
          distinct?: number;
          distribution?: {
            type?: string;
            labels?: string[];
            counts?: number[];
            [k: string]: unknown;
          };
          name?: string;
          profile_duration?: string;
          type?: string;
          schema_type?: string;
          [k: string]: unknown;
        };
        [k: string]: unknown;
      };
      assertion_results?: {
        tests?: {
          name?: string;
          status?: string;
          parameters?: {
            [k: string]: unknown;
          };
          expected?: {
            min?: number;
            [k: string]: unknown;
          };
          actual?: number;
          tags?: string[];
          [k: string]: unknown;
        }[];
        columns?: {
          SYMBOL?: {
            name: string;
            status: string;
            parameters: {
              [k: string]: unknown;
            };
            expected: {
              schema_type?: string;
              success?: boolean;
              [k: string]: unknown;
            };
            actual: {
              success?: boolean;
              [k: string]: unknown;
            };
            tags: string[];
            [k: string]: unknown;
          }[];
          NAME?: {
            name: string;
            status: string;
            parameters: {
              [k: string]: unknown;
            };
            expected: {
              schema_type?: string;
              success?: boolean;
              [k: string]: unknown;
            };
            actual: {
              success?: boolean;
              [k: string]: unknown;
            };
            tags: string[];
            [k: string]: unknown;
          }[];
          START_DATE?: {
            name: string;
            status: string;
            parameters: {
              [k: string]: unknown;
            };
            expected: {
              schema_type?: string;
              success?: boolean;
              [k: string]: unknown;
            };
            actual: {
              success?: boolean;
              [k: string]: unknown;
            };
            tags: string[];
            [k: string]: unknown;
          }[];
          END_DATE?: {
            name: string;
            status: string;
            parameters: {
              [k: string]: unknown;
            };
            expected: {
              schema_type?: string;
              success?: boolean;
              [k: string]: unknown;
            };
            actual: {
              success?: boolean;
              [k: string]: unknown;
            };
            tags: string[];
            [k: string]: unknown;
          }[];
          DESCRIPTION?: {
            name: string;
            status: string;
            parameters: {
              [k: string]: unknown;
            };
            expected: {
              schema_type?: string;
              success?: boolean;
              [k: string]: unknown;
            };
            actual: {
              success?: boolean;
              [k: string]: unknown;
            };
            tags: string[];
            [k: string]: unknown;
          }[];
          EXCHANGE_CODE?: {
            name: string;
            status: string;
            parameters: {
              [k: string]: unknown;
            };
            expected: {
              schema_type?: string;
              success?: boolean;
              [k: string]: unknown;
            };
            actual: {
              success?: boolean;
              [k: string]: unknown;
            };
            tags: string[];
            [k: string]: unknown;
          }[];
          MARKET?: {
            name: string;
            status: string;
            parameters: {
              [k: string]: unknown;
            };
            expected: {
              schema_type?: string;
              success?: boolean;
              [k: string]: unknown;
            };
            actual: {
              success?: boolean;
              [k: string]: unknown;
            };
            tags: string[];
            [k: string]: unknown;
          }[];
          COUNTRY?: {
            name: string;
            status: string;
            parameters: {
              [k: string]: unknown;
            };
            expected: {
              schema_type?: string;
              success?: boolean;
              [k: string]: unknown;
            };
            actual: {
              success?: boolean;
              [k: string]: unknown;
            };
            tags: string[];
            [k: string]: unknown;
          }[];
          SECTOR?: {
            name: string;
            status: string;
            parameters: {
              [k: string]: unknown;
            };
            expected: {
              schema_type?: string;
              success?: boolean;
              [k: string]: unknown;
            };
            actual: {
              success?: boolean;
              [k: string]: unknown;
            };
            tags: string[];
            [k: string]: unknown;
          }[];
          INDUSTRY?: {
            name: string;
            status: string;
            parameters: {
              [k: string]: unknown;
            };
            expected: {
              schema_type?: string;
              success?: boolean;
              [k: string]: unknown;
            };
            actual: {
              success?: boolean;
              [k: string]: unknown;
            };
            tags: string[];
            [k: string]: unknown;
          }[];
          RECOMMENDATION_KEY?: {
            name: string;
            status: string;
            parameters: {
              [k: string]: unknown;
            };
            expected: {
              schema_type?: string;
              success?: boolean;
              [k: string]: unknown;
            };
            actual: {
              success?: boolean;
              [k: string]: unknown;
            };
            tags: string[];
            [k: string]: unknown;
          }[];
          [k: string]: unknown;
        };
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  id?: string;
  created_at?: string;
  datasource?: {
    name?: string;
    type?: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
