lint:
	@npm run lint
.PHONY: lint

dev:
	@npm run start
.PHONY: dev

cleanup:
	@npm run cleanup
.PHONY: cleanup

build-single:
	@npm run build:single
.PHONY: build-single

build-comparison:
	@npm run build:comparison
.PHONY: build-single

build-all:
	@npm run build:all
.PHONY: build-all
