name: Run dbt tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [ '3.9', '3.10', '3.11' ]
        dbt: [ "dbt-core>=1.4,<1.5", "dbt-core>=1.5" ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest "${{ matrix.dbt }}"
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run tests
        run: |
          python -mpytest tests/test_dbt_manifest_compatible.py tests/test_dbt_integeration.py
