name: Run dbt tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [ '3.9', '3.10', '3.11' ]
        dbt: [ "dbt-core>=1.3,<1.4", "dbt-core>=1.4,<1.5", "dbt-core>=1.5" ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest "${{ matrix.dbt }}"
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run tests
        run: |
          set +e
          output=$(python -c "from dbt import version as v" 2>&1)
          exit_code=$?
          set -e

          if [ $exit_code -eq 0 ]; then
              python -mpytest tests/test_dbt_manifest_compatible.py tests/test_dbt_integeration.py
          else
              # https://github.com/dbt-labs/dbt-core/issues/6203#issuecomment-1319112890
              echo "Skip! dbt-core v1.3 only works with python less than 3.11"
          fi


          
