name: Release PipeRider CLI Nightly Build
on:
  schedule:
    - cron: '0 18 * * 0,1,2,3,4' # run at 2 AM (UTC + 8) every working day
  workflow_dispatch:
    branches:
      - main
    inputs:
      version_postfix:
        description: 'Version postfix'
        required: true
        type: string
        default: 'manually'

jobs:
  build-nightly-release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Release to PyPi
        run: |
          # put config includes tracking api key
          echo "$CONFIG" > ./piperider_cli/data/CONFIG

          # generate pypirc
          echo "$PYPIRC" > $HOME/.pypirc

          # change package name to piperider-nightly
          sed -i.bak "s/name='piperider'/name='piperider-nightly'/" setup.py


          # update version number
          echo "Nightly build version: $(date '+%Y%m%d')"
          if [ "$VERSION_POSTFIX" != "" ]; then
            echo "Manually version postfix: $VERSION_POSTFIX"
            sed -i.bak "s/\$/$(date '+%Y%m%d')-$VERSION_POSTFIX/" piperider_cli/VERSION
          else
            sed -i.bak "s/\$/$(date '+%Y%m%d')/" piperider_cli/VERSION
          fi
          echo ::set-output name=nightly_version::$(cat piperider_cli/VERSION)

          # release to PyPI
          make release
        env:
          PYPIRC: ${{ secrets.PYPI_NIGHTLY }}
          CONFIG: ${{ secrets.CONFIG }}
          VERSION_POSTFIX: ${{ inputs.version_postfix || '' }}

      - name: Mark Sentry Release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: development
          ignore_empty: true
          ignore_missing: true
          version: ${{ steps.vars.outputs.nightly_version }}
