# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# Should only affect changes pushed to static_report directory, when merging to `main`

name: Node.js - Build & Commit to CLI data/report/**

on:
  pull_request: # Reminder: for first-time detection only!
    
  push:
    paths:
      - "static_report"
    branches: # Reminder: Revert to 'main' before PR to 'main'
      - testing/sc-27084/on-merge-push-statics-build

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: static_report

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci
    - run: npm run build
    # - uses: stefanzweifel/git-auto-commit-action@v4
    #   with:
    #       commit_message: Automation - built report statics to CLI data/report
